#!/bin/bash

title () {
  echo -ne "\e]0;"
  echo -n "$@"
  echo -ne "\a"
}


ps1_func () {
    last=$?

    color=""
    if [[ $last != 0 ]] ; then
        color="\e[1;31m"
    else
        color="\e[1;32m"
    fi

    git_branch=""
    if [[ -d ".git" ]]; then
        git_branch=$(git branch | grep '\*' | sed -e 's/\* //')
        git_status=$(git status -s | wc -l)
        if [[ $git_status != 0 ]]; then
            git_branch+=" \e[1;31m+"
        fi
        git_branch=" \e[1;35m$git_branch \e[0m"
    fi


    PS1=$(title "\w")
    PS1+=$git_branch
    PS1+=$color
    PS1+="> \e[m"

}

PROMPT_COMMAND='ps1_func'
