#! /bin/sh

picom -b

xrdb .Xresources

~/.fehbg

# title
bspc monitor -d "terminal" "browser" "social" "other"

# 4ules
bspc rule -a TelegramDesktop desktop="^3"
bspc rule -a libreoffice desktop="^4"
bspc rule -a Inkscape desktop="^4"
bspc rule -a ffplay state=floating sticky=on

# borders
bspc config border_width         0
bspc config window_gap           16


bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config -n $(bspc query -N -n) border_width 0

# colors
bspc config normal_border_color "#cccccc9a"
bspc config active_border_color "#cccccc9a"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#cccccc9a"

# config sets
$HOME/.config/polybar/launch.sh

# remap  escape and control
setxkbmap -option ctrl:nocaps
xcape -e  'Control_L=Escape'

# cusror speed
xset r rate 200 50

# pkill -x flashfocus; flashfocus -t 200 & 

pkill -x unclutter; unclutter -idle 2 -b
# launch sxhkd
pkill -x sxhkd; sxhkd &
