#!/usr/bin/env bash

out="$HOME/Media/videos/"$(date +%y-%m-%d_%T)'.mp4'


notify-send 'Recording started' 

ffmpeg -f x11grab  -i :0.0 -f alsa -i default -crf 25 -pix_fmt yuv420p $out 2>/dev/null



copy_file="${out}-copy"
mv $out $copy_file

ffmpeg -y -i $copy_file -itsoffset 0.5 -i $copy_file \
       -map 0:v -map 1:a $out

rm $copy_file

notify-send 'Recording stopped' "file saved to ${out}"

